export const cassetteColorVariations = [
  {
    label: 'SufamiTurbo',
    backColor: '#a8a8a8',
    colorSpineTop: '#6dbf5b',
    colorSpineBottom: '#a8a8a8',
    frontcolorTop: '#6dbf5b',
    frontcolorBottom: '#6dbf5b',
    loadingLogoBack: '#000000',
    loadingLogoSpine: '#FFFFFF',
    loadingLogoFront: '#FFFFFF',
    nfcLogoBack: '#000000',
    nfcLogoSpine: '#FFFFFF',
    nfcLogoFront: '#FFFFFF',
  },
  {
    label: 'ps2',
    backColor: '#000000',
    colorSpineTop: '#000000',
    colorSpineBottom: '#FFFFFF',
    frontcolorTop: '#000000',
    frontcolorBottom: '#000000',
    loadingLogoBack: '#FFFFFF',
    loadingLogoSpine: '#FFFFFF',
    loadingLogoFront: '#FFFFFF',
    nfcLogoBack: '#0000FF',
    nfcLogoSpine: '#0000FF',
    nfcLogoFront: '#0000FF',
  },
  {
    label: 'steam',
    backColor: '#000000',
    colorSpineTop: '#102241',
    colorSpineBottom: '#000000',
    frontcolorTop: '#102241',
    frontcolorBottom: '#102241',
    loadingLogoBack: '#FFFFFF',
    loadingLogoSpine: '#FFFFFF',
    loadingLogoFront: '#FFFFFF',
    nfcLogoBack: '#FFFFFF',
    nfcLogoSpine: '#FFFFFF',
    nfcLogoFront: '#FFFFFF',
  },
  {
    label: 'msdos',
    backColor: '#A9A9A9',
    colorSpineTop: '#A9A9A9',
    colorSpineBottom: '#A9A9A9',
    frontcolorTop: '#A9A9A9',
    frontcolorBottom: '#A9A9A9',
    loadingLogoBack: '#000000',
    loadingLogoSpine: '#000000',
    loadingLogoFront: '#000000',
    nfcLogoBack: '#000000',
    nfcLogoSpine: '#000000',
    nfcLogoFront: '#000000',
  }
]

export const referencColorTable = {
  backColor: '#FFFF00',
  colorSpineTop: '#00FF00',
  colorSpineBottom: '#FF00FF',
  frontcolorTop: '#00FFFF',
  frontcolorBottom: '#FF0000',
  loadingLogoBack: '#1000FF',
  loadingLogoSpine: '#2000FF',
  loadingLogoFront: '#3000FF',
  nfcLogoBack: '#FF0010',
  nfcLogoSpine: '#FF0020',
  nfcLogoFront: '#FF0030',
}